### ISSUE TITLE
build error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'

### ISSUE THREAD

**Issue by bshanks-cov** [shcv/parenmedic#1]
```$ zig build -Doptimize=ReleaseSafe
build.zig:9:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
/home/username/bin/zig-x86_64-linux-0.16.0-dev.627+e6e4792a5/lib/std/Build.zig:770:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_26480: /home/username/bin/zig-x86_64-linux-0.16.0-dev.627+e6e4792a5/lib/std/Build.zig:2214:33
    main: /home/username/bin/zig-x86_64-linux-0.16.0-dev.627+e6e4792a5/lib/compiler/build_runner.zig:400:29
    5 reference(s) hidden; use '-freference-trace=7' to see all references
```

I'm using zig-x86_64-linux-0.16.0-dev.627+e6e4792a5

**Comment by codeasone** [comment]
I get the same failure with `zig 0.15.2` (latest at time of writing) but the project builds fine with `zig 0.14.1`.
